# Generated by Django 3.0.8 on 2020-07-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200725_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='phone',
        ),
    ]
